package blog.anirbanm.chart.model.am.common;

import blog.anirbanm.chart.viewmodel.types.Department;

import java.util.List;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 16 23:27:51 IST 2018
// ---------------------------------------------------------------------
public interface ChartModule extends ApplicationModule {
    List<Department> buildDataModel();
}

